version: '3.8'

services:
  app:
    build: .
    container_name: laravel-app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      DB_CONNECTION: pgsql
      DB_HOST: dpg-d1jlhom3jp1c73edt4eg-a.singapore-postgres.render.com
      DB_PORT: 5432
      DB_DATABASE: imax
      DB_USERNAME: imax_user
      DB_PASSWORD: OqpTbRyUNsqCzF6JLrlpDQvTAcpxmnDL
    working_dir: /var/www
